# ~/.tmuxinator/config.yml

name: config
root: ~/

windows:
  - main:
      root: ~/PersonalConfigs
      layout: main-horizontal
      panes:
         - vim -O .vimrc .zshrc
         -
         -
  - vim:
      root: ~/PersonalConfigs
      layout: main-horizontal
      panes:
        - vim_pane:
          - vim vim/after/plugin/hiSnazzy.vim
        - vim_folder:
          - cd ~/.vim
          - ls
        - raw:
          - cd /usr/share/vim/vim80
          - ls
