# ~/.tmuxinator/config.yml

name: config
root: ~/

windows:
  - main:
      root: ~/PersonalConfigs
      layout: main-horizontal
      panes:
        - vim_pane:
          - vim -O .vimrc .zshrc
        - folder:
          - ls
        - something:
          - ls
  - vim:
      root: ~/PersonalConfigs
      layout: main-horizontal
      panes:
        - vim_pane:
          - vim .vimrc
        - vim_folder:
          - cd ~/.vim
          - ls
        - raw:
          - cd /usr/share/vim/vim80
          - ls
  - tmux:
      root: ~/PersonalConfigs
      layout: main-horizontal
      panes:
        - vim single_scripts/tmux_template.conf
        - rubypanel:
          - cd ./single_scripts
          - when-changed -iv ./tmux_template.conf 'ruby ./color_config.rb'
        - echo `tput sitm`italics`tput ritm`

