# ~/.tmuxinator/dev.yml

name: dev
root: ~/

windows:
  - github-tools:
      root: ~/dev/js/node/github-tools
      layout: main-vertical
      panes:
        - vim
        - ls
  - monzo-gatekeeper:
      root: ~/dev/js/node/monzo-gatekeeper
      layout: main-vertical
      panes:
        - vim
        - ls
  - advent:
      root: ~/dev/advent
      layout: main-vertical
      panes:
        - vim
        - ls
  - functional-light:
      root: ~/dev/js/frontend-masters/functional-light/exercises
      layout: main-vertical
      panes:
        - vim
        - ls
  - gql-basic:
      root: ~/dev/js/graphql/gql-basic
      layout: main-vertical
      panes:
        - vim
        - ls
  - pr-dashboard:
      root: ~/Service/pr-dashboard
      layout: main-vertical
      panes:
        - vim
        - npm start
        - ls
        - curl "http://localhost:1234" | jq
