# ~/.tmuxinator/dev.yml

name: dev
root: ~/

windows:
  - pancake:
      root: ~/dev/js/node/pancake-api
      layout: main-vertical
      panes:
        - vim
        - ls
  - pr-dashboard:
      root: ~/Service/pr-dashboard
      layout: main-vertical
      panes:
        - vim
        - ls
  - node-apps:
      root: ~/dev/js/node
      layout: main-vertical
      panes:
        - vim
        - ls
  - advent:
      root: ~/dev/advent
      layout: main-vertical
      panes:
        - vim
        - ls
  - fem:
      root: ~/dev/frontend-masters
      layout: main-vertical
      panes:
        - vim
        - ls
